default_provider = "age"

[providers.age]
type = "age"
recipients = ["age1nlqfv0ptcfs7ssuuq8c06nprslcvwg9qpt6kf0ex20jhnknjmsqsrqf96k"]

[secrets]
AZURE_OPENAI_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMzFsTlN6RWJtSVprWERrYTRVQzdoaFhTM0J0ZHRkS01JNmtwSWZnWmhBCnJlZjNtd1hTR3JQR3hiNXpsRlZZYmJiRzhVTXIrdHRBbXlKMzAycWJWblkKLT4gYkktZ3JlYXNlIChpQHMgaC4KTW9ta0tqU0V4RVhlNlUyWEZ1RVROU0doajg2K1lEYVVuM0FJb2JPYkdaNlR4OWRhTkZNNytzZ3ExNVV4bFpYTwpYMmp6SjJzaGFBCi0tLSBEUnBzZjljYkgxS0x0K2dPNGg4blhlOW5ob0ZlbWpKV296dkp1VTZoMS9BCtPR7hmQUVCfhHXRhLc6OBwoA1N9GcN+0SgmBaYbeINE6vVj5AKyNI0Mw1EfhrKtXJXGDXYKlvlAbZqOCIbyRkQ=" }
AZURE_OPENAI_ENDPOINT= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MXRMMTl1Y1ZxZVh4b051bnRyUTgvLzd4cDEwZlQ1czZuS2c3NjZkb2pvCnBMZEtrZ0hhV2ZCUzNZLzBPZVV4ZDdpdUQyYXY5dlFjeGp6WmIxNHFpYnMKLT4ge2NRZHhaLWdyZWFzZSB0ZDFMCmNQYmluTEMvM3RvMHpSMWhSWkQ2RDIxaUNsdlpQa0lrYlEyd0s3RmVTT2FEUU4vVlpBd2lhQQotLS0gSkg3ZjJGbnBJUXcyczZ6MW50Q1NQNC9NYk1SRGswZW0wUkVMd1pEZ1huYwrpWx97rp6mmK0o6ppuSbfZlzUcjALCp+Je1a27DQLw2c9bWpq7Vh8LlXEWLs/1T78Nue6y2oNPXNwQF1GTxIuLeyP4c40=" }
