[tools]
bun = "latest"
fnox = "latest"
opencode = "latest"
shfmt = "latest" # .sh formatter

[env]
_.source = "scripts/env.sh"
# Alumnium envs
ALUMNIUM_LOG_LEVEL = "${ALUMNIUM_LOG_LEVEL:-debug}"
ALUMNIUM_MODEL = "${ALUMNIUM_MODEL:-azure_openai}"
ALUMNIUM_PLAYWRIGHT_NEW_TAB_TIMEOUT = "2000"
AZURE_OPENAI_API_VERSION = "${AZURE_OPENAI_API_VERSION:-2025-03-01-preview}"
# Tool envs
OPENCODE_CONFIG_DIR = "./.agents"
FORCE_COLOR = "1" # Force colors, i.e., for `bun --filter test`

[settings]
lockfile = true
idiomatic_version_file_enable_tools = ["node", "bun", "potery", "python"]

[tasks."mcp/start"]
run = "fnox exec --if-missing error -- bun ./packages/core/src/cli.ts mcp"
quiet = true
raw = true

[tasks."mcp/inspect"]
run = "cd packages/core && fnox exec --if-missing error -- ALUMNIUM_LOG_FILENAME=mcp-inspect.log bunx @modelcontextprotocol/inspector bun ./src/cli.ts mcp"

[tasks."server/start"]
run = "fnox exec --if-missing error -- bun ./packages/core/src/cli.ts server"

[tasks."clean/logs"]
run = "rm -rf ./.alumnium/logs/*"
