[tasks.install]
depends = ["//:install"]

[tasks.clean]
run = "rm -rf .alumnium dist"

[tasks.build]
run = "./scripts/build.ts"
description = "Build CLI bins, core npm and CLI pip packages"
depends = ["install", "build/generate"]
sources = [
  "src/**/*",
  "scripts/build.ts",
  "package.json",
  "tsconfig.json",
  "tsconfig.build.json",
  "*.md",
]
outputs = ["dist/**/*"]

[tasks."build/generate"]
run = { task = "build/generate:bundles" }

[tasks."build/generate:bundles"]
run = "./scripts/generate-bundles.ts | xargs oxfmt"
description = "Generates code bundles to enable building single-file executable"
depends = "install"
sources = [
  "scripts/generate-bundles.ts",
  # TODO: Move prompts generation into the script
  "src/server/agents/prompts/prompts.ts",
  "src/drivers/scripts/*.js",
  "src/server/agents/prompts/**/*.md",
]
outputs = [
  "src/server/agents/prompts/bundledPrompts.ts",
  "src/drivers/scripts/bundledScripts.ts",
]

[tasks.test]
run = [{ task = "test/unit" }, { task = "test/system:all" }]

[tasks."test/unit"]
run = "bun vitest --project unit run"
depends = "install"

[tasks."test/unit:watch"]
run = "bun vitest --project unit"
depends = "install"

[tasks."test/system"]
usage = '''
arg "<driver>" help="Driver to use for system tests" {
  choices "selenium" "playwright" "appium-ios" "appium-android"
  default "selenium"
}
'''
run = "ALUMNIUM_DRIVER={{usage.driver}} ./scripts/test-system.sh"
depends = "install"

[tasks."test/system:all"]
run = [
  { task = "test/system:selenium" },
  { task = "test/system:playwright" },
  { task = "test/system:appium-ios" },
  { task = "test/system:appium-android" },
]

[tasks."test/system:selenium"]
run = [{ task = "test/system selenium" }]

[tasks."test/system:playwright"]
run = [{ task = "test/system playwright" }]

[tasks."test/system:appium-ios"]
run = [{ task = "test/system appium-ios" }]

[tasks."test/system:appium-android"]
run = [{ task = "test/system appium-android" }]

[tasks.lint]
run = "bun oxlint ."
depends = "install"

[tasks."lint:fix"]
run = "bun oxlint --fix ."
depends = "install"

[tasks.format]
run = "bun oxfmt ."
depends = "install"

[tasks."format:check"]
run = "bun oxfmt . --check"
depends = "install"

[tasks.types]
depends = "//:types/ts"

[tasks."types:watch"]
depends = "//:types/ts:watch"
