[tasks."test/unit"]
run = "bun vitest --project unit run"

[tasks."test/unit:watch"]
run = "bun vitest --project unit"

[tasks."test/system:playwright"]
run = "fnox exec -- env ALUMNIUM_LOG_LEVEL=debug ALUMNIUM_LOG_FILENAME=test-system.log ALUMNIUM_DRIVER=playwright ALUMNIUM_PLAYWRIGHT_HEADLESS=true bun vitest --project system run"

[tasks."test/system:selenium"]
run = "fnox exec -- env ALUMNIUM_LOG_LEVEL=debug ALUMNIUM_LOG_FILENAME=test-system.log ALUMNIUM_DRIVER=selenium bun vitest --project system run"

[tasks.build]
run = "./scripts/build.ts"
description = "Build CLI bins, core npm and CLI pip packages"

[tasks."generate/bundles"]
run = "./scripts/generate-bundles.ts | xargs oxfmt"
description = "Generates code bundles to enable building single-file executable"

[tasks."server/daemon"]
run = "fnox exec --if-missing error -- bun ./src/cli/bin.ts server --daemon --wait-for --force"

[tasks."server/daemon:kill"]
run = "fnox exec --if-missing error -- bun ./src/cli/bin.ts server --kill --force"