#!/usr/bin/env bun

// This script generates helper files for the Alumnium single-file executable.

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadAgentPrompts } from "../src/server/agents/prompts/prompts.js";

const curName = fileURLToPath(import.meta.url);
const curDir = path.dirname(curName);

await Promise.all([bundleDriverScripts(), bundleAgentPrompts()]);

async function bundleDriverScripts() {
  const scriptsDir = path.resolve(curDir, "../src/drivers/scripts");

  const [waiterSource, waitForSource] = await Promise.all([
    fs.readFile(path.resolve(scriptsDir, "waiter.js"), "utf-8"),
    fs.readFile(path.resolve(scriptsDir, "waitFor.js"), "utf-8"),
  ]);

  await fs.writeFile(
    path.resolve(scriptsDir, "bundledScripts.ts"),
    `// This file is auto-generated by scripts/generate.ts. Do not edit it directly.

export const waiterScriptSource = ${JSON.stringify(waiterSource)};

export const waitForScriptSource = ${JSON.stringify(waitForSource)};
`,
  );
}

async function bundleAgentPrompts() {
  const prompts = await loadAgentPrompts();

  await fs.writeFile(
    path.resolve(curDir, "../src/server/agents/prompts/bundledPrompts.ts"),
    `// This file is auto-generated by scripts/generate.ts. Do not edit it directly.

import type { AgentPrompts } from "./prompts.js";

export const agentPrompts = ${JSON.stringify(prompts, null, 2)} as AgentPrompts;
`,
  );
}
