// This file is auto-generated by scripts/generate-types-scan-schema.ts. Do not edit it directly.

import z from "zod";

export abstract class LchainSchema {
  static MessageThinking = z.object({
    type: z.literal("thinking"),
    thinking: z.string(),
    signature: z.string().exactOptional(),
  });

  static MessageText = z.object({
    type: z.literal("text"),
    text: z.string(),
    annotations: z.array(z.unknown()).exactOptional(),
  });

  static MessageFunctionCallData = z.object({
    name: z.string(),
    args: z.record(z.string(), z.unknown()),
    id: z.string(),
  });

  static MessageFunctionCall = z.object({
    type: z.literal("functionCall"),
    functionCall: this.MessageFunctionCallData,
  });

  static MessageReasoning = z.object({
    type: z.literal("reasoning"),
    reasoning: z.string(),
  });

  static MessageToolUseCaller = z.object({
    type: z.union([z.literal("direct"), z.string()]),
  });

  static MessageToolUse = z.object({
    type: z.literal("tool_use"),
    id: z.string(),
    name: z.string(),
    input: z.record(z.string(), z.unknown()),
    caller: this.MessageToolUseCaller,
  });

  static MessageReasoningContentData = z.object({
    text: z.string(),
    signature: z.string(),
  });

  static MessageReasoningContent = z.object({
    type: z.literal("reasoning_content"),
    reasoningText: this.MessageReasoningContentData,
  });

  static MessageContent = z.discriminatedUnion("type", [
    this.MessageThinking,
    this.MessageText,
    this.MessageFunctionCall,
    this.MessageReasoning,
    this.MessageToolUse,
    this.MessageReasoningContent,
  ]);

  static ToolCall = z.object({
    type: z.literal("tool_call"),
    id: z.string(),
    name: z.string(),
    args: z.record(z.string(), z.unknown()),
  });

  static MessageDataToolCall = z.discriminatedUnion("type", [this.ToolCall]);

  static ReasoningSummary = z.object({
    type: z.literal("summary_text"),
    text: z.string(),
  });

  static Reasoning = z.object({
    id: z.string(),
    type: z.literal("reasoning"),
    summary: z.array(this.ReasoningSummary),
  });

  static MessageDataAdditionalKwargsReasoning = z.discriminatedUnion("type", [
    this.Reasoning,
  ]);

  static MessageDataAdditionalKwargsUsageCacheCreation = z.object({
    ephemeral_5m_input_tokens: z.number(),
    ephemeral_1h_input_tokens: z.number(),
  });

  static MessageDataAdditionalKwargsUsage = z.object({
    input_tokens: z.number(),
    cache_creation_input_tokens: z.number(),
    cache_read_input_tokens: z.number(),
    cache_creation: this.MessageDataAdditionalKwargsUsageCacheCreation,
    output_tokens: z.number(),
    service_tier: z.union([z.literal("standard"), z.string()]),
    inference_geo: z.string(),
  });

  static FunctionCallFunction = z.object({
    name: z.string(),
    arguments: z.string(),
  });

  static FunctionCall = z.object({
    index: z.literal(0).exactOptional(),
    id: z.string(),
    type: z.literal("function"),
    function: this.FunctionCallFunction,
  });

  static MessageDataAdditionalKwargsToolCallsItem = z.discriminatedUnion(
    "type",
    [this.FunctionCall],
  );

  static MessageDataAdditionalKwargs = z.object({
    finishReason: z.union([z.literal("STOP"), z.string()]).exactOptional(),
    index: z.number().exactOptional(),
    __gemini_function_call_thought_signatures__: z
      .record(z.string(), z.string())
      .exactOptional(),
    finishMessage: z.string().exactOptional(),
    reasoning: this.MessageDataAdditionalKwargsReasoning.exactOptional(),
    parsed: z.record(z.string(), z.unknown()).exactOptional(),
    __openai_function_call_ids__: z
      .record(z.string(), z.string())
      .exactOptional(),
    model: z.string().exactOptional(),
    id: z.string().exactOptional(),
    type: z.union([z.literal("message"), z.string()]).exactOptional(),
    role: z.union([z.literal("assistant"), z.string()]).exactOptional(),
    stop_reason: z.union([z.literal("tool_use"), z.string()]).exactOptional(),
    stop_sequence: z.null().exactOptional(),
    stop_details: z.null().exactOptional(),
    usage: this.MessageDataAdditionalKwargsUsage.exactOptional(),
    function_call: z.undefined().exactOptional(),
    tool_calls: z
      .array(this.MessageDataAdditionalKwargsToolCallsItem)
      .exactOptional(),
    reasoning_content: z.union([z.string(), z.undefined()]).exactOptional(),
  });

  static UsageMetadataInputTokenDetails = z.object({
    cache_read: z.number().exactOptional(),
    cache_creation: z.number().exactOptional(),
    audio: z.union([z.undefined(), z.number()]).exactOptional(),
  });

  static UsageMetadataOutputTokenDetails = z.object({
    reasoning: z.number().exactOptional(),
    audio: z.union([z.undefined(), z.number()]).exactOptional(),
  });

  static UsageMetadata = z.object({
    input_tokens: z.number(),
    output_tokens: z.number(),
    total_tokens: z.number(),
    input_token_details: this.UsageMetadataInputTokenDetails.exactOptional(),
    output_token_details: this.UsageMetadataOutputTokenDetails.exactOptional(),
  });

  static ResponseMetadataTokenUsage = z.object({
    promptTokens: z.number(),
    completionTokens: z.number(),
    totalTokens: z.number(),
  });

  static ResponseMetadataEstimatedTokenUsage = z.object({
    promptTokens: z.number().exactOptional(),
    completionTokens: z.number().exactOptional(),
    totalTokens: z.number().exactOptional(),
  });

  static ResponseMetadataMetadata = z.object({});

  static MetadataOutputText = z.object({
    type: z.literal("output_text"),
    annotations: z.array(z.unknown()),
    logprobs: z.array(z.unknown()),
    text: z.string(),
    parsed: z.record(z.string(), z.unknown()).exactOptional(),
  });

  static MetadataOutput = z.discriminatedUnion("type", [
    this.MetadataOutputText,
  ]);

  static OutputMessage = z.object({
    id: z.string(),
    type: z.literal("message"),
    status: z.union([z.literal("completed"), z.string()]),
    content: z.array(this.MetadataOutput),
    role: z.union([z.literal("assistant"), z.string()]),
  });

  static OutputFunctionCall = z.object({
    id: z.string(),
    type: z.literal("function_call"),
    status: z.literal("completed"),
    arguments: z.string(),
    call_id: z.string(),
    name: z.string(),
  });

  static ResponseMetadataOutputItem = z.discriminatedUnion("type", [
    this.Reasoning,
    this.OutputMessage,
    this.OutputFunctionCall,
  ]);

  static ResponseMetadataUsagePromptTokensDetails = z.object({
    cached_tokens: z.number(),
    text_tokens: z.number().exactOptional(),
    audio_tokens: z.number().exactOptional(),
    image_tokens: z.number().exactOptional(),
  });

  static CompletionTokensDetails = z.object({
    reasoning_tokens: z.number(),
    audio_tokens: z.number().exactOptional(),
    accepted_prediction_tokens: z.number().exactOptional(),
    rejected_prediction_tokens: z.number().exactOptional(),
  });

  static ResponseMetadataUsage = z.object({
    input_tokens: z.number().exactOptional(),
    cache_creation_input_tokens: z.number().exactOptional(),
    cache_read_input_tokens: z.number().exactOptional(),
    cache_creation:
      this.MessageDataAdditionalKwargsUsageCacheCreation.exactOptional(),
    output_tokens: z.number().exactOptional(),
    service_tier: z.string().exactOptional(),
    inference_geo: z.string().exactOptional(),
    prompt_tokens: z.number().exactOptional(),
    completion_tokens: z.number().exactOptional(),
    total_tokens: z.number().exactOptional(),
    prompt_tokens_details:
      this.ResponseMetadataUsagePromptTokensDetails.exactOptional(),
    completion_tokens_details: this.CompletionTokensDetails.exactOptional(),
    prompt_cache_hit_tokens: z.number().exactOptional(),
    prompt_cache_miss_tokens: z.number().exactOptional(),
    inputTokens: z.number().exactOptional(),
    outputTokens: z.number().exactOptional(),
    totalTokens: z.number().exactOptional(),
    num_sources_used: z.number().exactOptional(),
    cost_in_usd_ticks: z.number().exactOptional(),
    cacheReadInputTokens: z.number().exactOptional(),
    cacheWriteInputTokens: z.number().exactOptional(),
  });

  static ResponseMetadataMetrics = z.object({ latencyMs: z.number() });

  static ResponseMetadataInternal = z.object({
    httpStatusCode: z.number(),
    requestId: z.string(),
    extendedRequestId: z.undefined(),
    cfId: z.undefined(),
    attempts: z.number(),
    totalRetryDelay: z.number(),
  });

  static ResponseMetadata = z.object({
    tokenUsage: this.ResponseMetadataTokenUsage.exactOptional(),
    finishReason: z.union([z.literal("STOP"), z.string()]).exactOptional(),
    index: z.number().exactOptional(),
    finishMessage: z.string().exactOptional(),
    id: z.string().exactOptional(),
    estimatedTokenUsage:
      this.ResponseMetadataEstimatedTokenUsage.exactOptional(),
    model_provider: z.string().exactOptional(),
    model: z.string().exactOptional(),
    created_at: z.union([z.number(), z.string()]).exactOptional(),
    incomplete_details: z.null().exactOptional(),
    metadata: this.ResponseMetadataMetadata.exactOptional(),
    object: z.union([z.literal("response"), z.string()]).exactOptional(),
    output: z.array(this.ResponseMetadataOutputItem).exactOptional(),
    status: z.union([z.literal("completed"), z.string()]).exactOptional(),
    user: z.null().exactOptional(),
    service_tier: z.union([z.literal("default"), z.string()]).exactOptional(),
    model_name: z.string().exactOptional(),
    stop_reason: z.union([z.literal("tool_use"), z.string()]).exactOptional(),
    stop_sequence: z.null().exactOptional(),
    stop_details: z.null().exactOptional(),
    usage: this.ResponseMetadataUsage.exactOptional(),
    type: z.union([z.literal("message"), z.string()]).exactOptional(),
    role: z.union([z.literal("assistant"), z.string()]).exactOptional(),
    finish_reason: z
      .union([z.literal("tool_calls"), z.string()])
      .exactOptional(),
    system_fingerprint: z.string().exactOptional(),
    stopReason: z.union([z.literal("tool_use"), z.string()]).exactOptional(),
    metrics: this.ResponseMetadataMetrics.exactOptional(),
    $metadata: this.ResponseMetadataInternal.exactOptional(),
    prompt: z.number().exactOptional(),
    completion: z.number().exactOptional(),
    done: z.boolean().exactOptional(),
    done_reason: z.union([z.literal("stop"), z.string()]).exactOptional(),
    total_duration: z.number().exactOptional(),
    load_duration: z.number().exactOptional(),
    prompt_eval_count: z.number().exactOptional(),
    prompt_eval_duration: z.number().exactOptional(),
    eval_count: z.number().exactOptional(),
    eval_duration: z.number().exactOptional(),
  });

  static ToolCallChunk = z.object({
    name: z.string(),
    args: z.string(),
    id: z.string(),
    index: z.number(),
    type: z.literal("tool_call_chunk"),
  });

  static MessageData = z.object({
    content: z.union([z.array(this.MessageContent), z.string()]),
    tool_calls: z.array(this.MessageDataToolCall),
    additional_kwargs: this.MessageDataAdditionalKwargs,
    usage_metadata: z.union([this.UsageMetadata, z.undefined()]),
    invalid_tool_calls: z.array(z.unknown()),
    response_metadata: this.ResponseMetadata,
    id: z.string(),
    name: z.unknown().exactOptional(),
    type: z.union([z.literal("ai"), z.string()]).exactOptional(),
    tool_call_chunks: z.array(this.ToolCallChunk).exactOptional(),
  });

  static Message = z.object({
    type: z.union([z.literal("ai"), z.string()]),
    data: this.MessageData,
  });

  static StoredGeneration = z.object({
    text: z.string(),
    message: this.Message,
  });
}

export namespace LchainSchema {
  export type MessageThinking = z.infer<typeof LchainSchema.MessageThinking>;

  export type MessageText = z.infer<typeof LchainSchema.MessageText>;

  export type MessageFunctionCallData = z.infer<
    typeof LchainSchema.MessageFunctionCallData
  >;

  export type MessageFunctionCall = z.infer<
    typeof LchainSchema.MessageFunctionCall
  >;

  export type MessageReasoning = z.infer<typeof LchainSchema.MessageReasoning>;

  export type MessageToolUseCaller = z.infer<
    typeof LchainSchema.MessageToolUseCaller
  >;

  export type MessageToolUse = z.infer<typeof LchainSchema.MessageToolUse>;

  export type MessageReasoningContentData = z.infer<
    typeof LchainSchema.MessageReasoningContentData
  >;

  export type MessageReasoningContent = z.infer<
    typeof LchainSchema.MessageReasoningContent
  >;

  export type MessageContent = z.infer<typeof LchainSchema.MessageContent>;

  export type ToolCall = z.infer<typeof LchainSchema.ToolCall>;

  export type MessageDataToolCall = z.infer<
    typeof LchainSchema.MessageDataToolCall
  >;

  export type ReasoningSummary = z.infer<typeof LchainSchema.ReasoningSummary>;

  export type Reasoning = z.infer<typeof LchainSchema.Reasoning>;

  export type MessageDataAdditionalKwargsReasoning = z.infer<
    typeof LchainSchema.MessageDataAdditionalKwargsReasoning
  >;

  export type MessageDataAdditionalKwargsUsageCacheCreation = z.infer<
    typeof LchainSchema.MessageDataAdditionalKwargsUsageCacheCreation
  >;

  export type MessageDataAdditionalKwargsUsage = z.infer<
    typeof LchainSchema.MessageDataAdditionalKwargsUsage
  >;

  export type FunctionCallFunction = z.infer<
    typeof LchainSchema.FunctionCallFunction
  >;

  export type FunctionCall = z.infer<typeof LchainSchema.FunctionCall>;

  export type MessageDataAdditionalKwargsToolCallsItem = z.infer<
    typeof LchainSchema.MessageDataAdditionalKwargsToolCallsItem
  >;

  export type MessageDataAdditionalKwargs = z.infer<
    typeof LchainSchema.MessageDataAdditionalKwargs
  >;

  export type UsageMetadataInputTokenDetails = z.infer<
    typeof LchainSchema.UsageMetadataInputTokenDetails
  >;

  export type UsageMetadataOutputTokenDetails = z.infer<
    typeof LchainSchema.UsageMetadataOutputTokenDetails
  >;

  export type UsageMetadata = z.infer<typeof LchainSchema.UsageMetadata>;

  export type ResponseMetadataTokenUsage = z.infer<
    typeof LchainSchema.ResponseMetadataTokenUsage
  >;

  export type ResponseMetadataEstimatedTokenUsage = z.infer<
    typeof LchainSchema.ResponseMetadataEstimatedTokenUsage
  >;

  export type ResponseMetadataMetadata = z.infer<
    typeof LchainSchema.ResponseMetadataMetadata
  >;

  export type MetadataOutputText = z.infer<
    typeof LchainSchema.MetadataOutputText
  >;

  export type MetadataOutput = z.infer<typeof LchainSchema.MetadataOutput>;

  export type OutputMessage = z.infer<typeof LchainSchema.OutputMessage>;

  export type OutputFunctionCall = z.infer<
    typeof LchainSchema.OutputFunctionCall
  >;

  export type ResponseMetadataOutputItem = z.infer<
    typeof LchainSchema.ResponseMetadataOutputItem
  >;

  export type ResponseMetadataUsagePromptTokensDetails = z.infer<
    typeof LchainSchema.ResponseMetadataUsagePromptTokensDetails
  >;

  export type CompletionTokensDetails = z.infer<
    typeof LchainSchema.CompletionTokensDetails
  >;

  export type ResponseMetadataUsage = z.infer<
    typeof LchainSchema.ResponseMetadataUsage
  >;

  export type ResponseMetadataMetrics = z.infer<
    typeof LchainSchema.ResponseMetadataMetrics
  >;

  export type ResponseMetadataInternal = z.infer<
    typeof LchainSchema.ResponseMetadataInternal
  >;

  export type ResponseMetadata = z.infer<typeof LchainSchema.ResponseMetadata>;

  export type ToolCallChunk = z.infer<typeof LchainSchema.ToolCallChunk>;

  export type MessageData = z.infer<typeof LchainSchema.MessageData>;

  export type Message = z.infer<typeof LchainSchema.Message>;

  export type StoredGeneration = z.infer<typeof LchainSchema.StoredGeneration>;
}
