// This file is auto-generated by scripts/generate-types-scan-schema.ts. Do not edit it directly.

import z from "zod";

export abstract class LchainGeneration {
  static Reasoning = z.object({
    id: z.string(),
    type: z.literal("reasoning"),
    summary: z.array(z.unknown()),
  });

  static AdditionalKwargsReasoning = z.discriminatedUnion("type", [
    this.Reasoning,
  ]);

  static ToolCallFunctionData = z.object({
    name: z.string(),
    arguments: z.string(),
  });

  static ToolCallFunction = z.object({
    index: z.literal(0).exactOptional(),
    id: z.string(),
    type: z.literal("function"),
    function: this.ToolCallFunctionData,
  });

  static ToolCall = z.discriminatedUnion("type", [this.ToolCallFunction]);

  static AdditionalKwargs = z.object({
    reasoning: this.AdditionalKwargsReasoning.exactOptional(),
    __openai_function_call_ids__: z
      .record(z.string(), z.string())
      .exactOptional(),
    reasoning_content: z.union([z.string(), z.undefined()]).exactOptional(),
    function_call: z.undefined().exactOptional(),
    tool_calls: z.array(this.ToolCall).exactOptional(),
    parsed: z.record(z.string(), z.unknown()).exactOptional(),
  });
}

export namespace LchainGeneration {
  export type Reasoning = z.infer<typeof LchainGeneration.Reasoning>;

  export type AdditionalKwargsReasoning = z.infer<
    typeof LchainGeneration.AdditionalKwargsReasoning
  >;

  export type ToolCallFunctionData = z.infer<
    typeof LchainGeneration.ToolCallFunctionData
  >;

  export type ToolCallFunction = z.infer<
    typeof LchainGeneration.ToolCallFunction
  >;

  export type ToolCall = z.infer<typeof LchainGeneration.ToolCall>;

  export type AdditionalKwargs = z.infer<
    typeof LchainGeneration.AdditionalKwargs
  >;
}
