#!/usr/bin/env bun

// This script generates helper files for the Alumnium single-file executable.

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadAgentPrompts } from "../src/server/agents/prompts/prompts.ts";

const HEADER =
  "// This file is auto-generated by scripts/generate-bundles.ts. Do not edit it directly.";

const curName = fileURLToPath(import.meta.url);
const curDir = path.dirname(curName);

const bundles = await Promise.all([
  bundleDriverScripts(),
  bundleAgentPrompts(),
]);

// NOTE: We write paths to stdout to use as oxfmt args
const bundlePaths = bundles
  .map((bundlePath) => JSON.stringify(bundlePath))
  .join(" ");
console.write(bundlePaths);

async function bundleDriverScripts() {
  const scriptsDir = path.resolve(curDir, "../src/drivers/scripts");

  const [waiterSource, waitForSource, findSelectorSource] = await Promise.all([
    fs.readFile(path.resolve(scriptsDir, "waiter.js"), "utf-8"),
    fs.readFile(path.resolve(scriptsDir, "waitFor.js"), "utf-8"),
    fs.readFile(path.resolve(scriptsDir, "findSelector.js"), "utf-8"),
  ]);

  const bundlePath = path.resolve(scriptsDir, "bundledScripts.ts");
  await fs.writeFile(
    bundlePath,
    `${HEADER}

export const waiterScriptSource = ${JSON.stringify(waiterSource)};

export const waitForScriptSource = ${JSON.stringify(waitForSource)};

export const findSelectorScriptSource = ${JSON.stringify(findSelectorSource)};
`,
  );
  return bundlePath;
}

async function bundleAgentPrompts() {
  const prompts = await loadAgentPrompts();

  const bundlePath = path.resolve(
    curDir,
    "../src/server/agents/prompts/bundledPrompts.ts",
  );
  await fs.writeFile(
    bundlePath,
    `${HEADER}

import type { AgentPrompts } from "./prompts.ts";

export const agentPrompts : AgentPrompts = ${JSON.stringify(prompts, null, 2)};
`,
  );
  return bundlePath;
}
