[tasks.install]
run = "bun install"

[tasks.clean]
run = "rm -rf dist/ public/install.sh public/install.ps1"

[tasks.build]
depends = ["build/paraglide"]
run = '''
bun run astro check
bun run astro build
'''

[tasks."generate/paraglide"]
run = "bun run paraglide-js compile --project ../../project.inlang --outdir ./src/texts --strategy baseLocale"
# sources = ["../../project.inlang/**/*", "messages/**/*"]
# outputs = ["src/texts/**/*"]

[tasks."generate/paraglide:watch"]
run = "bun run paraglide-js compile  --watch --project ../../project.inlang --outdir ./src/texts --strategy baseLocale"

[tasks."dev:build"]
run = "bun run astro preview"
depends = ["build"]

[tasks.dev]
run = "bun run astro dev --host 0.0.0.0"

[tasks."generate/install-scripts"]
run = "bun scripts/generate-install-scripts.ts"

[tasks."test/install-scripts"]
run = '''
sh public/install.sh
expected=$(mise //packages/typescript:version)
alumnium --version | grep -qF "$expected"
'''

[tasks."fetch/webvoyager"]
run = '''
curl https://raw.githubusercontent.com/steel-dev/leaderboard/refs/heads/main/src/data/webvoyager.json > \
  ./src/data/webvoyager.json
'''

[tasks."fetch/asciinema"]
run = "bun scripts/fetchAsciinemaMetadata.ts"
