// This file is auto-generated by scripts/generate-bundles.ts. Do not edit it directly.

import type { CursorSdkVendorManifest } from "./cursorSdkManifest.ts";

export const cursorSdkVendorManifest: CursorSdkVendorManifest = {
  sdkVersion: "1.0.23",
  packages: [
    {
      name: "@bufbuild/protobuf",
      version: "1.10.0",
      integrity:
        "sha512-QDdVFLoN93Zjg36NoQPZfsVH9tZew7wKDKyV5qRdj8ntT4wQCOradQjRaTdwMhWUYsgKsvCINKKm87FdEk96Ag==",
    },
    {
      name: "@connectrpc/connect",
      version: "1.7.0",
      integrity:
        "sha512-iNKdJRi69YP3mq6AePRT8F/HrxWCewrhxnLMNm0vpqXAR8biwzRtO6Hjx80C6UvtKJ5sFmffQT7I4Baecz389w==",
    },
    {
      name: "@connectrpc/connect-node",
      version: "1.7.0",
      integrity:
        "sha512-6vaPIkG/NyhxlYgytLoR9KYbPhczEboFB2OYWkA9qvUz1K7efXfeGrlRxoLtpa+r8VxyIOw73w5ktNe743nD+A==",
    },
    {
      name: "@connectrpc/connect-web",
      version: "1.7.0",
      integrity:
        "sha512-qyP0YOnUPRWwCc/VfsoydMJvkb7EyUPr2q9sHgBuJzbADjiqck1gKH5V5ZPzPhTLBvmz5UvG+wiZ5sMRQHU1MQ==",
    },
    {
      name: "@cursor/sdk",
      version: "1.0.23",
      integrity:
        "sha512-VIh8oW89XXACUkQqB2N8TaU3A/y2jQieF++VC6QqIqKhKRKj7kd+pzeh43MXusuPpebtxtEzqvjaCLlc1xbYTQ==",
    },
    {
      name: "@cursor/sdk-darwin-arm64",
      version: "1.0.23",
      integrity:
        "sha512-HpltGkIDFG+XgsETJho0OiOvGLyMKqZKhh4uXtD3ZKZcgTtLvKgbbU8jVgEMa3qodtfwPz5lpwAjs5jM1zOt6w==",
      os: "darwin",
      cpu: "arm64",
      bin: {
        rg: "bin/rg",
      },
    },
    {
      name: "@cursor/sdk-darwin-x64",
      version: "1.0.23",
      integrity:
        "sha512-sjRQVhU7UL3kYSR9DzY+BAwa/iFdnPvTI3E62mIhj/2ey3LEnhIhotZQ9ymNJ0wA5BfhC7Be+JYcSMDyHxxr1g==",
      os: "darwin",
      cpu: "x64",
      bin: {
        rg: "bin/rg",
      },
    },
    {
      name: "@cursor/sdk-linux-arm64",
      version: "1.0.23",
      integrity:
        "sha512-RizTwZ2Hhhaq8bnF3yGUZWBUvLA+/lExlTAg/5Levc9f7hNoDZViIP3XaVWY/8yzPAxypeds8tWacVIaAA2/Ig==",
      os: "linux",
      cpu: "arm64",
      bin: {
        rg: "bin/rg",
      },
    },
    {
      name: "@cursor/sdk-linux-x64",
      version: "1.0.23",
      integrity:
        "sha512-s93WBbi4hrE/uisTrEfNNH1m18bwfO6wmmsnIYQ3W3gbGBriFM1ZeroHxj1F6paMDE7o/dfUeW22lQ72rRZrSA==",
      os: "linux",
      cpu: "x64",
      bin: {
        rg: "bin/rg",
      },
    },
    {
      name: "@cursor/sdk-win32-x64",
      version: "1.0.23",
      integrity:
        "sha512-d1p1+tRJbNZTUqw8SPEW9OYtU02ynZysASDDvhpaEFtbPwGFUrez9sVbFHpbuXeOXL//H+faiHJanVFsUNfIZw==",
      os: "win32",
      cpu: "x64",
      bin: {
        rg: "bin/rg.exe",
      },
    },
    {
      name: "@fastify/busboy",
      version: "2.1.1",
      integrity:
        "sha512-vBZP4NlzfOlerQTnba4aqZoMhE/a9HY7HRqoOPaETQcSQuWEIyZMHGfVu6w9wGtGK5fED5qRs2DteVCjOH60sA==",
    },
    {
      name: "@statsig/client-core",
      version: "3.31.0",
      integrity:
        "sha512-SuxQD6TmVszPG7FoMKwTk/uyBuVFk7XnxI3T/E0uyb7PL7GNjONtfsoh+NqBBVUJVse0CUeSFfgJPoZy1ZOslQ==",
    },
    {
      name: "@statsig/js-client",
      version: "3.31.0",
      integrity:
        "sha512-LFa5E0LjT6sTfZv3sNGoyRLSZ1078+agdgOA+Vm1ecjG+KbSOfBLTW7hMwimrJ29slRwbYDzbtKaPJo/R37N2g==",
    },
    {
      name: "undici",
      version: "5.29.0",
      integrity:
        "sha512-raqeBD6NQK4SkWhQzeYKd1KmIG6dllBOTt55Rmkt4HtI9mwdWtJljnrXjAFUBLTSN67HWrOIZ3EPF4kjUw80Bg==",
    },
    {
      name: "zod",
      version: "3.25.76",
      integrity:
        "sha512-gzUt/qt81nXsFGKIFcC3YnfEAx5NkunCfnDlvuBSSFS02bcXu4Lmea0AFIUwbLWxWPx3d9p8S5QoaujKcNQxcQ==",
    },
  ],
};
