# Alumnium installer — generated by scripts/generate-install-scripts.ts
# irm https://alumnium.ai/install.ps1 | iex

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$AlumniumVersion = "{{VERSION}}"
$Checksums = @{
  "windows-x64"   = "{{CHECKSUM_windows_x64}}"
  "windows-arm64" = "{{CHECKSUM_windows_arm64}}"
}

if (-not [Environment]::Is64BitProcess) {
  Write-Error "Alumnium requires a 64-bit Windows."
  exit 1
}

$arch = if ($env:PROCESSOR_ARCHITECTURE -eq "ARM64") { "arm64" } else { "x64" }
$platform = "windows-$arch"
$checksum = $Checksums[$platform]

$binary = "alumnium-$AlumniumVersion-$platform.exe"
$url = "https://github.com/alumnium-hq/alumnium/releases/download/$AlumniumVersion/$binary"
$installDir = Join-Path $env:USERPROFILE ".alumnium" "bin"
$installPath = Join-Path $installDir "alumnium.exe"
$tmp = [System.IO.Path]::GetTempFileName() + ".exe"

try {
  Write-Output "Downloading alumnium $AlumniumVersion (windows-$arch)..."
  Invoke-WebRequest -Uri $url -OutFile $tmp -ErrorAction Stop

  Write-Host -NoNewline "Verifying checksum... "
  $actual = (Get-FileHash -Path $tmp -Algorithm SHA256).Hash.ToLower()
  if ($actual -ne $checksum) {
    Write-Error "Checksum mismatch!`n  expected: $checksum`n  actual:   $actual"
    exit 1
  }

  Write-Output "ok"

  New-Item -ItemType Directory -Force -Path $installDir | Out-Null
  Move-Item -Force $tmp $installPath

  # Add install dir to user PATH if missing
  $userPath = [Environment]::GetEnvironmentVariable("PATH", "User")
  if ($userPath -notlike "*$installDir*") {
    [Environment]::SetEnvironmentVariable("PATH", "$userPath;$installDir", "User")
    Write-Output "Added $installDir to your PATH (restart your shell to take effect)."
  }

  Write-Output ""
  Write-Output "Alumnium $AlumniumVersion installed to $installPath"
}
finally {
  if (Test-Path $tmp) { Remove-Item -Force $tmp -ErrorAction SilentlyContinue }
}
