name: Binaries
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Set Up Dev Env
        uses: ./.github/actions/setup

      - name: Build Dist
        run: mise //packages/typescript:build

      - name: Upload Binaries Artifacts
        uses: ./.github/actions/dist-artifacts
        with:
          name: build
          bin: true

      - name: Debug Session
        if: failure() && runner.debug == '1'
        uses: mxschmitt/action-tmate@v3
